# Generated by Django 4.2.5 on 2023-09-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_feathred',
            new_name='is_featured',
        ),
    ]
