# Generated by Django 4.2.5 on 2023-10-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_abount_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='abount_description',
            new_name='about_description',
        ),
    ]
